### ISSUE TITLE
Multiple cars are not showing

### ISSUE THREAD

**Issue by BonnyLindberg** [leeyuentuen/tibber_ev#3]
I have two cars connected to my Tibber account and only one is showing. I guess you are just processing the first element of the array returned from the API.

**Comment by leeyuentuen** [comment]
yes this should be the next step to support multiple cars

**Comment by BonnyLindberg** [comment]
Great! Thanks for the swift answer! 
Looking forward to the implementation. 😊👍

**Comment by leeyuentuen** [comment]
@BonnyLindberg maybe quick look on the beta version if you can see all the car info?
https://github.com/leeyuentuen/tibber_ev/releases/tag/0.1.1

**Comment by BonnyLindberg** [comment]
I tried it and sorry to say that it didn't show both cars. It now showed the other car though. 😊

**Comment by leeyuentuen** [comment]
maybe a second try?
just remove first existing data (because I have also change the config flow, we don't need friendly name anymore)
https://github.com/leeyuentuen/tibber_ev/releases/tag/0.1.2

i've try with dummy data, don't know how it should be in live
![image](https://github.com/leeyuentuen/tibber_ev/assets/1487966/39afc00a-25a9-449c-a4fd-441975593e7f)

**Comment by BonnyLindberg** [comment]
Argh. I'm not able to verify right now as my Kia has reached maximum daily vehicle checks. ☹
I will check when this limit has timed out. Sorry for that.
Still thanks for the swift updates. 😊👍

**Comment by BonnyLindberg** [comment]
I have now verified that it works! 😊👍
![image](https://github.com/leeyuentuen/tibber_ev/assets/48298216/29c4960c-6279-4c5d-95f6-f7a96c15d1df)
Thanks for the fast fixing! 
Great work! 🏆

**Comment by leeyuentuen** [comment]
> I have now verified that it works! 😊👍 ![image](https://user-images.githubusercontent.com/48298216/283718291-29c4960c-6279-4c5d-95f6-f7a96c15d1df.png) Thanks for the fast fixing! Great work! 🏆

great. i'll merge them soon to main and release for public

**Comment by leeyuentuen** [comment]
released here: https://github.com/leeyuentuen/tibber_ev/releases/tag/0.2
