### ISSUE TITLE
Error in manifest file for v0.2.

### ISSUE THREAD

**Issue by BonnyLindberg** [leeyuentuen/tibber_ev#6]
There is an error in the manifest file for version 0.2

![image](https://github.com/leeyuentuen/tibber_ev/assets/48298216/6f39dfc4-556f-4b4a-a023-56b149353e31)

Thess rows has the error:
"codeowners": ["leeyuentuen"]
"iot_class": "cloud_polling",

Comma missing on first row and a comma too much on the last. 😊

**Comment by leeyuentuen** [comment]
indeed, i've just release it

should be correct on this tag: https://github.com/leeyuentuen/tibber_ev/releases/tag/0.2.2

**Comment by BonnyLindberg** [comment]
Works fine in the new release! 😊👍

**Comment by leeyuentuen** [comment]
thanks for report, i'll close this Issue.
